### PR TITLE
Fixes #452

### LINKED ISSUE #452: Bug: getCode() does not properly handle null token data, may cause NullPointerException
The method getCode() retrieves token data from SharedPreferences and immediately passes it to Token.deserialize() without validating the value. If the stored value associated with a UUID is null, or if Token.deserialize() returns null, subsequent execution will trigger a NullPointerException.
This causes the app to crash rather than fail gracefully.
**File** (mobile/src/main/java/org/fedorahosted/freeotp/main/Adapter.java):  
``` java 
Token token = Token.deserialize(mSharedPreferences.getString(uuid, null));
Key key = mKeyStore.getKey(uuid, null);
code = token.getCode(key);
```
There is no null-check for:

- the stored string returned from SharedPreferences
- the token returned from Token.deserialize(...)

Thus, both token and code may be dereferenced without verification.

**Expected Behavior:**

If no token string is stored, or if deserialization fails, getCode() should:

- return a safe error Code instance, or
- throw a controlled exception (Not crash)

For example:
``` java
String stored = mSharedPreferences.getString(uuid, null);
if (stored == null) {
    return new Code("ERROR", 0);   // or handle appropriately
}
Token token = Token.deserialize(stored);
if (token == null) {
    return new Code("ERROR", 0);
}
```
When SharedPreferences.getString() returns null, or Token.deserialize() returns null, token.getCode(key) triggers:

- NullPointerException

leading to a crash rather than controlled failure.
This violates expected OTP-generation behavior and prevents users from retrieving codes safely.

### PR DESCRIPTION
**Pull request by abinash2512**
Added check for null values in stored and token, if null will return "ERROR" instead of an OTP token. Not entirely sure if I've handled this in the ideal way but it doesn't crash anymore if either value is null.

### CODE REVIEW

**Comment by joggee-fr** [comment]
Hi @abinash2512,
Could you modify your commit message to clearly explain the modifications you have done keeping the [link to the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue) in the commit message itself?

**Comment by abinash2512** [comment]
Hi @joggee-fr 
I have made the changes to the commit message to explain the differences and linked the issue in the commit message. Hope it's okay now.

File: mobile/src/main/java/org/fedorahosted/freeotp/main/Adapter.java [hunk 1]
```diff
@@ -285,7 +285,18 @@ public Code getCode(int position)
...
+                Log.e(LOGTAG, "Stored is null");
+                return new Code("ERROR", 15);
+            }
+            if (token == null){
+                Log.e(LOGTAG, "Token is null");
+                return new Code("ERROR", 15);
+            }
             Key key = mKeyStore.getKey(uuid, null);
             code = token.getCode(key);
             mSharedPreferences.edit().putString(uuid, token.serialize()).apply();
```
Comment (joggee-fr) [inline mobile/src/main/java/org/fedorahosted/freeotp/main/Adapter.java]: Note for myself, the token is updated in shared preferences as for HOTP counter value may have changed.

File: mobile/src/main/java/org/fedorahosted/freeotp/main/Adapter.java [hunk 2]
```diff
@@ -285,7 +285,18 @@ public Code getCode(int position)
...
         try {
             Log.i(LOGTAG, String.format("getCode: deserialize token"));
-            Token token = Token.deserialize(mSharedPreferences.getString(uuid, null));
+            String stored = mSharedPreferences.getString(uuid, null);
+            Token token = null;
+            if (stored != null) {
+                token = Token.deserialize(stored);
+            } else {
+                Log.e(LOGTAG, "Stored is null");
+                return new Code("ERROR", 15);
```
Comment (joggee-fr) [inline mobile/src/main/java/org/fedorahosted/freeotp/main/Adapter.java]: This Code construction is now repeated 3 times with these "special" values.

File: mobile/src/main/java/org/fedorahosted/freeotp/main/Adapter.java [hunk 3]
```diff
@@ -285,7 +285,18 @@ public Code getCode(int position)
...
+            }
+            if (token == null){
```
[the remark this answers is not in the document]
Comment (abinash2512) [reply mobile/src/main/java/org/fedorahosted/freeotp/main/Adapter.java]: Changes have been made in latest commit

**Comment by justin-stephenson** [comment]
Thank you for the PR @abinash2512
